package org.example

import java.sql.Connection
import java.sql.ResultSet
import kotlin.random.Random


/**
 * Computes the sum of two numbers of type `Number` and returns the result as a `Double`.
 * 
 * @param a The first number to be added, of a type extending `Number`.
 * @param b The second number to be added, of a type extending `Number`.
 * @return The sum of `a` and `b` as a `Double`.
 */
fun <T : Number> aPlusB(a: T, b: T): Double = a.toDouble() + b.toDouble()


/**
 * Executes the given SQL query on the provided database connection and returns the result as a list of lists.
 * Each inner list represents a row from the query result, and each element in this list is a column value.
 * 
 * @param db The database connection to be used for executing the query.
 * @param query The SQL query string to be executed.
 * @return A list of lists containing the query results, where each list represents a row.
 */
fun sqlite(db: Connection, query: String): List<List<Any?>> {
    db.createStatement().use { statement ->
        statement.executeQuery(query).use { resultSet ->
            val results = mutableListOf<List<Any?>>()
            val columnCount = resultSet.metaData.columnCount

            while (resultSet.next()) {
                val row = mutableListOf<Any?>()
                for (i in 1..columnCount) {
                    row.add(resultSet.getObject(i))
                }
                results.add(row)
            }
            return results
        }
    }
}


/**
 * Compares two items of type T based on their keys, which are generated by a key mapping function and are of type R.
 * The comparison is done using natural ordering of type R, and the function returns an integer as the result of this comparison.
 * 
 * @param keyMap A function that takes an item of type T and returns its key of type R which is used for comparison.
 * @param item1 The first item to be compared.
 * @param item2 The second item to be compared.
 * @return An integer representing the comparison result: 
 *         -1 if the key of item1 is less than the key of item2,
 *          1 if the key of item1 is greater than the key of item2,
 *          0 if the keys of both items are equal.
 */
fun <T, R : Comparable<R>> compare(keyMap: (T) -> R, item1: T, item2: T): Int {
    return when {
        keyMap(item1) < keyMap(item2) -> -1
        keyMap(item1) > keyMap(item2) -> 1
        else -> 0
    }
}


/**
 * Generates a random string composed of upper and lowercase alphabets.
 * 
 * @param length The desired length of the resulting string.
 * @return A string of randomly selected alphabets with the specified length.
 */
fun randomAlphabets(length: Int): String {
    val charPool = ('a'..'z') + ('A'..'Z')
    return (1..length)
        .map { charPool[Random.nextInt(0, charPool.size)] }
        .joinToString("")
}