name: "Apply issue labels to PR"

on:
  pull_request_target:
    types:
      - opened

jobs:
  label_on_pr:
    runs-on: ubuntu-latest

    permissions:
      contents: none
      issues: write
      pull-requests: read

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: pip install requests

      - name: Apply labels from linked issue to PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python ./bin/apply_labels.py
